### ISSUE TITLE
Ignored 'skipVisualTests' option 

### ISSUE THREAD

**Issue by jacekgrzybowski** [Huddle/grunt-phantomflow#4]
Hello,

I'm trying to disable phantomcss visual tests in `Gruntfile.js` for all of my `casper/phantomflow` test cases.

My config looks like this:

    grunt.initConfig({
        phantomflow: {
            my_app_name: {
              "includes": "test/casper/include",
              "debug": 2,
              "threads": 1,
              "createReport": true,
              "tests": "test/casper/",
              "skipVisualTests": true,
              "remoteDebug": true
            }
        },
        ...
    });

However, both `skipVisualTests` as well as `remoteDebug` options are ignored.

I use version 0.2.3:
    ├─┬ grunt-phantomflow@0.2.3
    │ └─┬ phantomflow@0.4.3
    │   ├─┬ phantomcss@0.9.3
    │   │ ├─┬ phantomjs@1.9.7-14

**Comment by jamescryer** [comment]
I think the config needs to be slightly more flexible.  I don't have the time right now, but I'll accept a PR that updates 
https://github.com/Huddle/grunt-phantomflow/blob/master/tasks/phantomflow.js to support these params

**Comment by jamescryer** [comment]
This should work since https://github.com/Huddle/grunt-phantomflow/commit/403b6a94b7dbf7f4e07c69d191968ea6b99cf338
